backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "ホームページ編集"
    files:
      - label: "トップページ"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - {label: "ページのタイトル", name: "title", widget: "string"}
          - {label: "本文", name: "body", widget: "markdown"}