backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "HTMLファイル"
    files:
      - file: "public/index.html" # 編集したいHTMLファイルの場所
        label: "トップページ"
        name: "index"
        fields: # ← この fields の中身が重要です！
          - {label: "ページのタイトル", name: "title", widget: "string"}
          - {label: "メインの文章", name: "body", widget: "markdown"}